

## Security
security:
  useOpenLDAP: false
  adminGroup: "TerrakubeAdmin"
  dexClientId: "terrakube"
  dexIssuerUri: "https://terrakube-api.appflex.io/dex"

## Dex
dex:
  config:
    issuer: https://terrakube-api.appflex.io/dex

    connectors:
      # 🔑 GitHub OIDC login
      - type: github
        id: github
        name: GitHub
        config:
          clientID: "Ov23liQUwQ10Bhm7Rodt"
          clientSecret: "493f3e0535dd4c8856a0b46b1dafb7bc30458516"
          redirectURI: "https://terrakube-api.appflex.io/dex/callback"
          orgs:
            - name: appflex   # optional, restrict login to your GitHub org

    staticClients:
      - id: terrakube
        redirectURIs:
          - "https://terrakube-ui.appflex.io"
          - "/device/callback"
          - "http://localhost:10000/login"
          - "http://localhost:10001/login"
        name: "terrakube"
        public: true

## Terraform Storage
storage:
  defaultStorage: false
  minio:
    accessKey: "root"
    secretKey: "q1w2e3r4100@"
    bucketName: "terrakube"
    endpoint: "http://minio.default.svc.cluster.local:9000"

## Ingress properties
ingress:
  useTls: true
  ui:
    domain: "terrakube-ui.appflex.io"
    tlsSecretName: appflex.io
  api:
    domain: "terrakube-api.appflex.io"
    tlsSecretName: appflex.io
  registry:
    domain: "terrakube-reg.appflex.io"
    tlsSecretName: appflex.io



    
