
global:
  host: terrakube.example.com   # replace with your domain

replicaCount: 3   # HA deployment

image:
  repository: azbuilder/terrakube
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: terrakube.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: terrakube-tls
      hosts:
        - terrakube.example.com

# Disable built-in PostgreSQL and use external DB
postgresql:
  enabled: false

externalDatabase:
  enabled: true
  host: terrakube-db.example.com   # your RDS/Aurora/CloudSQL endpoint
  port: 5432
  user: terrakube
  password: terrakubeStrongPass123
  database: terrakube

auth:
  oidc:
    enabled: true
    clientId: "terrakube-client"
    clientSecret: "super-secret-client"
    issuerUri: "https://accounts.google.com"  # example for Google OIDC

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2
    memory: 4Gi

persistence:
  enabled: true
  size: 20Gi
  storageClass: gp2   # or gp3/ssd depending on your cloud provider

nodeSelector: {}
tolerations: []
affinity: {}
