

## Security
security:
  useOpenLDAP: false
  adminGroup: "TerrakubeAdmin"
  dexClientId: "terrakube"
  dexIssuerUri: "https://terrakube-api.leadercapital.net/dex"


## Dex
dex:
  config:
    issuer: https://terrakube-api.leadercapital.net/dex

    connectors:
    - type: oidc
      name: keycloak
      id: keycloak
      config:
        issuer: https://auth.leaderdns.net/auth/realms/develop #http://<KEYCLOAK FQDN/IPADDR>:PORT/auth/realms/<Realm>
        clientID: terrakube
        clientSecret: <REDACTED>
        redirectURI: https://terrakube-api.leadercapital.net/dex/callback #https://<metal-lb or cloud LB>/dex/callback
        loadAllGroups: true
        scopes:
        - openid
        - profile
        - email
        - groups
        insecureSkipEmailVerified: true
        insecureEnableGroups: true
        userIDKey: email
        userNameKey: email

    staticClients:
    - id: terrakube
      redirectURIs:
      - 'https://terrakube-ui.leadercapital.net'
      - '/device/callback'
      - 'http://localhost:10000/login'
      - 'http://localhost:10001/login'
      name: 'terrakube'
      public: true


## Terraform Storage
storage:
  defaultStorage: false
  minio:
    accessKey: "root"
    secretKey: "q1w2e3r4100@"
    bucketName: "terrakube"
    endpoint: "http://minio.default.svc.cluster.local:9000"


## Ingress properties
ingress:
  useTls: true
  ui:
    domain: "terrakube-ui.leadercapital.net"
    tlsSecretName: leadercapital.net
  api:
    domain: "terrakube-api.leadercapital.net"
    tlsSecretName: leadercapital.net
  registry:
    domain: "terrakube-reg.leadercapital.net"
    tlsSecretName: leadercapital.net

